# FindMbedTLS.cmake — resolve against in-tree mbedtls targets built by native/CMakeLists.txt
if(TARGET mbedtls AND TARGET mbedcrypto AND TARGET mbedx509)
  set(MbedTLS_FOUND TRUE)
  if(NOT MbedTLS_INCLUDE_DIRS)
    get_target_property(_inc mbedtls INTERFACE_INCLUDE_DIRECTORIES)
    set(MbedTLS_INCLUDE_DIRS "${_inc}")
  endif()
  set(MbedTLS_LIBRARY mbedtls)
  set(MbedCrypto_LIBRARY mbedcrypto)
  set(MbedX509_LIBRARY mbedx509)
  if(NOT TARGET MbedTLS::mbedtls)
    add_library(MbedTLS::mbedtls ALIAS mbedtls)
  endif()
  if(NOT TARGET MbedTLS::mbedcrypto)
    add_library(MbedTLS::mbedcrypto ALIAS mbedcrypto)
  endif()
  if(NOT TARGET MbedTLS::mbedx509)
    add_library(MbedTLS::mbedx509 ALIAS mbedx509)
  endif()
endif()
